### ISSUE TITLE
Runtime panic

### ISSUE THREAD

**Issue by Laller** [crufter/nocrud#1]
You can't overwrite data.C:/gowork/src/github.com/opesun/chill/frame/top/top.go:93 (0x4678f0)
    com/opesun/chill/frame/top._func_002: err = fmt.Errorf(fmt.Sprint(r) + string(debug.Stack()))
C:/Users/ADMINI~1/AppData/Local/Temp/2/bindist579160455/go/src/pkg/runtime/proc.c:1443 (0x40fb36)
C:/gowork/src/github.com/opesun/chill/frame/impl/viewcontext/viewcontext.go:29 (0x5044ad)
    com/opesun/chill/frame/impl/viewcontext.(_ViewContext).Publish: panic("You can't overwrite data.")
C:/gowork/src/github.com/opesun/chill/modules/roller/roller.go:28 (0x5540dd)
    com/opesun/chill/modules/roller.(_C).Get: c.vctx.Publish("noun:", i)
C:/Users/ADMINI~1/AppData/Local/Temp/2/bindist579160455/go/src/pkg/reflect/value.go:521 (0x4b1fd2)
C:/Users/ADMINI~1/AppData/Local/Temp/2/bindist579160455/go/src/pkg/reflect/value.go:334 (0x4b08e8)
C:/gowork/src/github.com/opesun/chill/frame/mod/mod.go:74 (0x4f9142)
    com/opesun/chill/frame/mod.Method.Call: subj_out := reflect.Value(me).Call(subj_in)
C:/gowork/src/github.com/opesun/chill/frame/mod/file.go:0 (0x4f9c4f)
    com/opesun/chill/frame/mod.(_Method).Call: ???
C:/gowork/src/github.com/opesun/chill/frame/highlev/highlev.go:79 (0x51535a)
    com/opesun/chill/frame/highlev.(_HighLev).Run: err = ins.Method(desc.Sentence.Verb).Call(ret_rec, inp...)
C:/gowork/src/github.com/opesun/chill/frame/top/top.go:107 (0x4673cd)
    com/opesun/chill/frame/top.(_Top).route: ret, err := hl.Run(ctx.Db(), ctx.User(), deflev)
C:/gowork/src/github.com/opesun/chill/frame/top/top.go:52 (0x466bfa)
    com/opesun/chill/frame/top.(_Top).Route: err = t.route()
C:/gowork/src/github.com/opesun/chill/main.go:79 (0x401ada)
    _func_002: err = top.Route()
C:/Users/ADMINI~1/AppData/Local/Temp/2/bindist579160455/go/src/pkg/net/http/server.go:690 (0x444bf4)
C:/Users/ADMINI~1/AppData/Local/Temp/2/bindist579160455/go/src/pkg/net/http/server.go:926 (0x445822)
C:/Users/ADMINI~1/AppData/Local/Temp/2/bindist579160455/go/src/pkg/net/http/server.go:656 (0x444a42)
C:/Users/ADMINI~1/AppData/Local/Temp/2/bindist579160455/go/src/pkg/runtime/proc.c:271 (0x40dee2)

**Comment by crufter** [comment]
Semantics has changed, it won't panic now.
